language: r

services:
  - docker

os:
  - linux

r:
  - oldrel
  - release
  - devel

install:
  - docker build -t shiny-server .
  - docker run -d -p 127.0.0.1:80:80 --name shiny shiny-server

script:
  - docker ps | grep -q shiny
